// this file was auto generated by duriel, don't manually change it!

const en = require('./en.json');
const de = require('./de.json');
const es = require('./es.json');
const fi = require('./fi.json');
const fr = require('./fr.json');
const it = require('./it.json');
const pt = require('./pt.json');
const sv = require('./sv.json');

module.exports = { en, de, es, fi, fr, it, pt, sv };
