type: object
displayName: BusinessPartnerContact
description: Object representing all contacts associated with a given business partner. For field descriptions, see [model docs](https://github.com/OpusCapita/business-partner/wiki/BusinessPartnerContact.model)
properties:
    id:
        type: integer
    businessPartnerId:
        type: string
    title:
        type: string
    type:
        type: string
    firstName:
        type: string
    lastName:
        type: string
    email:
        type: string
        required: false
    phone:
        type: string
        required: false
    mobile:
        type: string
        required: false
    department:
        type: string
        required: false
    fax:
        type: string
        required: false
    changedBy:
        type: string
        required: false
    createdBy:
        type: string
    createdOn:
        type: string
    changedOn:
        type: string
        required: false
example: !include ../examples/BusinessPartnerContact.json
