BusinessPartner: !include BusinessPartner.raml
BusinessPartnerArray: !include BusinessPartnerArray.raml
BusinessPartnerAddress: !include BusinessPartnerAddress.raml
BusinessPartnerAddressArray: !include BusinessPartnerAddressArray.raml
BusinessPartnerBankAccount: !include BusinessPartnerBankAccount.raml
BusinessPartnerBankAccountArray: !include BusinessPartnerBankAccountArray.raml
BusinessPartnerContact: !include BusinessPartnerContact.raml
BusinessPartnerContactArray: !include BusinessPartnerContactArray.raml
BusinessPartnerCapability: !include BusinessPartnerCapability.raml
BusinessLink: !include BusinessLink.raml
BusinessLinkArray: !include BusinessLinkArray.raml
BusinessLinkConnection: !include BusinessLinkConnection.raml
