responses:
    406:
        description: The requested action is not permitted as it may result in an inconsistent data status.
        body:
            application/json:
                type: Error
