#%RAML 1.0
title: BusinessPartner Service Documentation
description: Service for working with business partner related data.
version: 1.0.0
baseUri: http://localhost
mediaType:
  - application/json
protocols:
  - http
  - https

types: !include schemas/index.raml
traits:
    acceptLanguage: !include traits/acceptLanguage.raml
    sendNotFound: !include traits/sendNotFound.raml
    sendConflict: !include traits/sendConflict.raml

/api: !include resourceTypes/businessLink.raml
/api: !include resourceTypes/businessPartner.raml
