#%RAML 1.0
title: BusinessPartner Service Documentation
description: Service for working with business partner related data.
version: 1.0.0
baseUri: http://localhost
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS

types: !include schemas/index.raml
traits:
  sendConflict: !include traits/sendConflict.raml
  sendFailedDependency: !include traits/sendFailedDependency.raml
  sendForbidden: !include traits/sendForbidden.raml
  sendNotPermitted: !include traits/sendNotPermitted.raml
  sendGeneralError: !include traits/sendGeneralError.raml
  sendNotFound: !include traits/sendNotFound.raml

/api: !include resourceTypes/businessLinks.raml
/api/business-partners: !include resourceTypes/businessPartners.raml
