displayName: BusinessPartners
description: Work with `BusinessPartner` objects.
/business-partners
    get:
        description: List of `BusinessPartner` objects.
        queryParameters:
            name:
                type: string
                required: false
                description: Limit the output to the businessParters with name contained in passed name.
                example: name=hardware
            id:
                type: string
                required: false
                description: Limits the output to the passed businessPartner ids.
                example: id=admin,foo,bar
            include:
                type: string
                required: false
                description: Additional, comma separated businessPartner associations to include. Existing associations are `addresses`, `contacts`, `bankAccounts`, and `capabilities`.
                example: include=addresses,contacts
            vatIdentificationNo:
                type: string
                required: false
                description: Limit output to given VAT ID.
                example: vatIdentificationNo=DE136752020
            globalLocationNo:
                type: string
                required: false
                description: Limit output to given global location number.
                example: globalLocationNo=1245678976543
            electronicAddress:
                type: string
                required: false
                description: Limit output to given electronic address according to ISO6523 codes. See https://www.galaxygw.com/iso6523/
                example: electronicAddress=9930:DE136752020
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerArray
    post:
        description: Adds a new business partner.
        body:
            application/json:
                type: BusinessPartnerNew
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartner
            409:
                description:
                    A business partner with the same id but different set of properties already exists.

/business-partners/{id}:
    uriParameters:
        id:
            type: string
            description: Identifier of a businessParnter.
    get:
        description: Single `BusinessPartner` object.
        queryParameters:
            include:
                type: string
                required: false
                description: Endpoint will return the included comma seperated models
                example: include=addresses
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartner
            404:
                description:
                    Business partner does not exist.
    put:
        description: Updates a business partner.
        body:
            application/json:
                type: BusinessPartnerNew
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartner
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data
    delete:
        description: Delete a business partner record.
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized


/business-partners/{businessPartnerId}/addresses:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all addresses assigned to the business partner
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerAddressArray
    post:
        description: Create address for a business partner
        body:
            application/json:
                type: BusinessPartnerAddress
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerAddress
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/business-partners/{businessPartnerId}/addresses/{addressId}:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
        addressId:
            type: number
            description: Identifeir of business partner address
    get:
        description: Get single `BusinessPartnerAddress` object assigned to the `BusinessPartner`
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerAddress
            404:
                description:
                    An address for this business partner does not exist.
    put:
        description: Update address for a business partner
        body:
            application/json:
                type: BusinessPartnerAddress
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerAddress
            404:
                description:
                    An address for this business partner does not exist.
    delete:
        description: Delete BusinessPartnerAddress record
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data


/business-partners/{businessPartnerId}/bank-accounts:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all bank accounts assigned to the business partner
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerBankAccountArray
    post:
        description: Create bank account for a business partner
        body:
            application/json:
                type: BusinessPartnerBankAccount
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerBankAccount
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/business-partners/{businessPartnerId}/bank-accounts/{bankAccountId}:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
        bankAccountId:
            type: number
            description: Identifeir of business partner bank account
    get:
        description: Get single `BusinessPartnerBankAccount` object assigned to the `BusinessPartner`
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerBankAccount
            404:
                description:
                    An bank account for this business partner does not exist.
    put:
        description: Update bank account for a business partner
        body:
            application/json:
                type: BusinessPartnerBankAccount
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerBankAccount
            404:
                description:
                    A bank account for this business partner does not exist.
    delete:
        description: Delete BusinessPartnerBankAccount record
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data


/business-partners/{businessPartnerId}/contacts:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all contacts assigned to the business partner
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerContactArray
    post:
        description: Create contact for a business partner
        body:
            application/json:
                type: BusinessPartnerContact
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerContact
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/business-partners/{businessPartnerId}/contacts/{bankAccountId}:
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
        bankAccountId:
            type: number
            description: Identifeir of business partner contact
    get:
        description: Get single `BusinessPartnerContact` object assigned to the `BusinessPartner`
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerContact
            404:
                description:
                    An contact for this business partner does not exist.
    put:
        description: Update contact for a business partner
        body:
            application/json:
                type: BusinessPartnerContact
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerContact
            404:
                description:
                    A contact for this business partner does not exist.
    delete:
        description: Delete BusinessPartnerContact record
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data


/business-partners/{businessPartnerId}/organization
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all business partners belonging to organization of given business partner.
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerArray

/business-partners/{businessPartnerId}/parents
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all parent business partners (parent companies) of given business partner.
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerArray

/business-partners/{businessPartnerId}/children
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
    get:
        description: Get all child business partners (daughter companies) of given business partner.
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerArray


/business-partners/{businessPartnerId}/capabilities/{capabilityId}
    uriParameters:
        businessPartnerId:
            type: string
            description: Identifier of a business partner.
        capabilityId:
            type: string
            description: capability type. Can be either `eInvoice-send`, `order`, `catalog` or `fulfillment`.
    put:
        description: Add capability to a given business partner
        responses:
            200:
                body:
                    application/json:
                        type: BusinessPartnerCapability
    delete:
        description: Delete capability from a given business partner
        responses:
            200:
                body:
                    application/json:
                        type: {}
